name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache gradle dependencies
      uses: actions/cache@v1
      env:
        cache-name: cache-gradle
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-

    - name: Build with Gradle
      run: ./gradlew build --no-daemon || ./gradlew build --no-daemon

    - name: Upload Jar
      uses: actions/upload-artifact@v1
      with:
        name: CC-Tweaked
        path: build/libs

  lint-lua:
    name: Lint Lua
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Lint Lua code
      run: |
        test -d bin || mkdir bin
        test -f bin/illuaminate || wget -q -Obin/illuaminate https://squiddev.cc/illuaminate/bin/illuaminate
        chmod +x bin/illuaminate
        bin/illuaminate lint
